/* Generated By:JavaCC: Do not edit this line. SqlGrammarConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int ASTERISK = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int GT = 10;
  /** RegularExpression Id. */
  int LT = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int WORD = 14;
  /** RegularExpression Id. */
  int ALPHABET = 15;
  /** RegularExpression Id. */
  int INT_VALUE = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"*\"",
    "<EQUAL>",
    "\">\"",
    "\"<\"",
    "\"AND\"",
    "<STRING>",
    "<WORD>",
    "<ALPHABET>",
    "<INT_VALUE>",
    "<DIGIT>",
    "\";\"",
    "\",\"",
    "\".\"",
  };

}
